== gollum
* **启动**
```bash
sudo docker run -d -p 80:4567 --name gollum -v ~/wiki:/root/wikidata suttang/gollum
```
* **支持配置文件**
```bash
#修改Asciidoc文件后缀
sudo docker run -d -p 80:4567 --name gollum -v ~/wiki:/ gollum/wiki alpine-gollum:1.1 --config /gollum/wiki/config.rb --css /gollum/wiki /custom.css 
```

== Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "C:/Users/dishui/Desktop/sublime\ file", "/home/vagrant/wiki"
  config.vm.synced_folder "D:/docker/images", "/home/vagrant/src/docker/images"
  config.vm.define "u1" do |u1|
    u1.vm.box = "ubuntu-14.04"
    u1.vm.hostname = "u1"
    u1.vm.network "private_network", ip: "192.168.137.11",name: "VirtualBox Host-Only Ethernet Adapter"
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
```
{{{{{{ blue-modern
title Authentication Sequence

哈希->游戏: Authentication Request
note right of Bob: Bob thinks about it
Bob->Alice: Authentication Response

[->A: text
A->]: text

A->+B: text
B-->-A: text
}}}}}}



. Step 1
. Step 2
.. Step 2a
.. Step 2b
. Step 3


first term:: definition of first term
section term:: definition of second term


[qanda]
What is Asciidoctor?::
  An implementation of the AsciiDoc processor in Ruby.
What is the answer to the Ultimate Question?:: 42


Operating Systems::
  Linux:::
    . Fedora
      * Desktop
    . Ubuntu
      * Desktop
      * Server
  BSD:::
    . FreeBSD
    . NetBSD

Cloud Providers::
  PaaS:::
    . OpenShift
    . CloudBees
  IaaS:::
    . Amazon EC2
    . Rackspace


- [*] checked
- [x] also checked
- [ ] not checked
-     normal list item




Footnotes

A statement.footnote:[Clarification about this statement.]

A bold statement.footnoteref:[disclaimer,Opinions are my own.]

Another bold statement.footnoteref:[disclaimer]



```html
<snippet>
    <content><![CDATA[
+
```$1

```
]]></content>
    <!-- Optional: Set a tabTrigger to define how to trigger the snippet -->
    <tabTrigger>q</tabTrigger>
    <!-- Optional: Set a scope to limit where the snippet will trigger -->
    <!-- <scope>source.python</scope> -->
</snippet>
```


链接: https://pan.baidu.com/s/1sjWYZ4x 密码: smes